version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build Application
          command: npm run build
      - run:
          name: Save Cache
          command: |
            mkdir -p ~/.npm && cp -R node_modules ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - build

  sonarcloud_scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: SonarCloud Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=UndeadRonin99_Payment-Portal \
              -Dsonar.organization=undeadronin99 \
              -Dsonar.sources=src \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build-and-scan:
    jobs:
      - build
      - sonarcloud_scan:
          requires:
            - build
